### ISSUE TITLE
victoriametrics vs vmsingle

### ISSUE THREAD

**Issue by Karsonito** [patsevanton/victoriametrics-rpm#17]
Hi!
Will the victoriametrics package be supported again?
Or it's better to migrate to vmsingle?

Thanks for maintenance of VM!

**Comment by denisgolius** [comment]
> vmsingle

Hi @Karsonito !
Yep, the main idea was to save backward compatibility victoriametrics for some time but now it better to move to vmsingle.

**Comment by Karsonito** [comment]
Thanks. Issue is closed
