### ISSUE TITLE
el9 support

### ISSUE THREAD

**Issue by IvanKolomiets** [patsevanton/victoriametrics-rpm#21]
I would be really appreciated if you could add support epel-9-x86_64 to the repo https://copr-be.cloud.fedoraproject.org/results/antonpatsev/VictoriaMetrics/

**Comment by denisgolius** [comment]
@patsevanton PTAL

**Comment by patsevanton** [comment]
@IvanKolomiets I added. Try later a few hours.

**Comment by IvanKolomiets** [comment]
looks good, thank you :)
