### ISSUE TITLE
Only 1 last builds in 2 weeks limit

### ISSUE THREAD

**Issue by Karsonito** [patsevanton/victoriametrics-rpm#3]
Is there a limit on the number of packages available in COPR?
Currently I can downgrade only to previous version of VM
```
[root@centos ~]# yum --showduplicates list victoriametrics
Loaded plugins: copr, langpacks
Installed Packages
victoriametrics.x86_64                                         1.50.1-1
Available Packages
victoriametrics.x86_64                                         1.50.0-1
victoriametrics.x86_64                                         1.50.1-1
```

Is it possible to keep more versions in COPR?

**Comment by patsevanton** [comment]
Hello!
I don`t know...

**Comment by Karsonito** [comment]
https://docs.pagure.org/copr.copr/user_documentation.html#how-long-do-you-keep-the-builds

> How long do you keep the builds? ¶
> 
> We keep one build for each package in one project indefinitely. All other builds (old packages, failed builds) are deleted after 14 days.
> 
> Note that we keep the build with the greatest EPOCH:NAME-VERSION-RELEASE, even though that build might not be the newest one. Also, if there are two builds of the same package version, it is undefined which one is going to be kept.

Only 2 weeks and gone... Oops. What about making it live longer in other place? For i.e. in github or other place?

**Comment by Karsonito** [comment]
The problem with removed packages still not solved?

> https://docs.pagure.org/copr.copr/user_documentation.html#how-long-do-you-keep-the-builds
> 
> > How long do you keep the builds? ¶
> > We keep one build for each package in one project indefinitely. All other builds (old packages, failed builds) are deleted after 14 days.
> > Note that we keep the build with the greatest EPOCH:NAME-VERSION-RELEASE, even though that build might not be the newest one. Also, if there are two builds of the same package version, it is undefined which one is going to be kept.
> 
> Only 2 weeks and gone... Oops. What about making it live longer in other place? For i.e. in github or other place?
> 
> Previous build 1.59 was deleted after yesterdays build 1.60 (

**Comment by patsevanton** [comment]
Yes. Not solved. I think this issue of copr.fedorainfracloud.org

**Comment by Karsonito** [comment]
Thanks. We have to accept it )
