### ISSUE TITLE
Plans for supporting this repository

### ISSUE THREAD

**Issue by denisgolius** [patsevanton/victoriametrics-rpm#5]
What are your plans to support this repository, [vmctl](https://copr.fedorainfracloud.org/coprs/antonpatsev/vmctl/) repository and maintain community repository https://copr.fedorainfracloud.org/coprs/antonpatsev/VictoriaMetrics/  ? I mean how long do you plan to support them?

**Comment by patsevanton** [comment]
Added package vmagent, vmalert, vmauth, vmbackup, vmctl, vmrestore, vmsingle.
Please check.
